### ISSUE TITLE
Non-existent function: plugin_archisw_install

### ISSUE THREAD

**Issue by philippeplatiau** [ericferon/glpi-archisw#1]
Bonjour, 

J'ai ce message dans la partie "plugins". Je ne peux donc pas l'installer. 
Je ne trouve aucune autre erreur. 
Une idée ? 

Cordialement, 

Philippe 
GLPI 9.1.6

**Comment by ericferon** [comment]
Effectivement, le code avait été supprimé erronément lors d'une substitution de texte en masse, ainsi que dans beaucoup d'autres fichiers.
J'ai republié le code sous le même numéro de version.
Vous pouvez supprimer votre ancien téléchargement et le télécharger à nouveau.
Bien cordialement,
Eric

**Comment by philippeplatiau** [comment]
Merci pour votre retour. Mais désolé, j'ai maintenant une autre erreur : erreur 500

Et dans le error.log d'apache : 

Tue Jul 03 14:46:59.913601 2018] [:error] [pid 36297] [client **********:43226] PHP Fatal error:  Call to undefined method DB::TableExists() in /usr/share/glpi/plugins/archisw/hook.php on line 33, referer: https://**********/front/plugin.php

**Comment by philippeplatiau** [comment]
(j'ai caché mon ip et le nom du serveur, évidemment)

**Comment by ericferon** [comment]
Dans ce fichier hook.php, à la ligne 33, il y a un appel $DB->TableExists, mais pas DB::TableExists.
Pouvez-vous vérifier votre fichier ?
Bien cordialement,

**Comment by philippeplatiau** [comment]
Oui, c'est bien ca
​. Dans le fichier j'ai ceci ​
:

 !$DB->TableExists

Est-ce dû à la version GLPI 9.1.6 ​? Est-ce bien compatible ?
Je vais exécuter le fichier SQL et voir si le plugin est quand même
utilisable, malgré le problème d'installation.
Je vous tiens au courant

Philippe



Le mar. 3 juil. 2018 à 17:18, Eric Feron <notifications@github.com> a
écrit :

**Comment by philippeplatiau** [comment]
Non, cela ne fonctionne pas... C'est bizarre, dès qu'il tente d'exécuter
DB->TableExists, j'ai une erreur dans Apache : DB::TableExists

[Wed Jul 04 08:46:16.387190 2018] [:error] [pid 42337] [client
xxxxxx:48862] PHP Fatal error:  Call to undefined method DB::TableExists()
in /usr/share/glpi/plugins/archisw/hook.php on line 33, referer:
https://xxx.yyy.be/front/plugin.php

[Wed Jul 04 08:49:19.013531 2018] [:error] [pid 43657] [client
xxxxxx:48898] PHP Fatal error:  Call to undefined method DB::TableExists()
in /usr/share/glpi/plugins/archisw/inc/profile.class.php on line 184,
referer: https://xxx.yyy.be/front/plugin.php

...

**Comment by ericferon** [comment]
C'est dû au fait que vous utilisez GLPI 9.1.x : la fonction TableExists est "deprecated" en 9.2 et j'ai remplacé tous les appels à TableExists par $DB->TableExists, afin d'éviter les messages (inutiles) dans php-errors.log.
Je vais supprimer la compatibilité du plugin avec 9.1 (je l'avais d'abord développé en 9.1, mais le code a encore évolué après avoir migré en 9.2).
Je vous conseille donc de migrer vers 9.2 si vous voulez utiliser ce plugin ou les autres que j'ai écrits.
Bien cordialement,
Eric

**Comment by philippeplatiau** [comment]
Merci beaucoup pour ces précisions, Eric.
Pas de soucis. La migration est prévue prochainement. J'ai un peu retardé
la migration car certains plugins n'étaient ou ne sont plus disponibles en
9.2
Par exemple : le "renamer" fonctionnait encore sous 9.1 , le hidefields
n'est visiblement pas dispo pour 9.2.
Et puis le FusionInventory... Apparemment, il faut y passer un peu plus de
temps...

Cordialement

Philippe
