### ISSUE TITLE
Link with a project

### ISSUE THREAD

**Issue by redfish0** [ericferon/glpi-archisw#10]
Hi,
When I link my application with a project I get (In the project, at "Applications") the following error in debug mode), in fact this happens all the time even without any project linked...

PHP Notice: Undefined variable: PluginArchiswSwcomponent in /var/www/glpi/plugins/archisw/inc/swcomponent_item.class.php at line 435

Fatal error: Uncaught Error: Call to a member function maybeRecursive() on null in /var/www/glpi/plugins/archisw/inc/swcomponent_item.class.php:435 Stack trace: #0 /var/www/glpi/plugins/archisw/inc/swcomponent_item.class.php(122): PluginArchiswSwcomponent_Item::showForItem(Object(Project)) #1 /var/www/glpi/inc/commonglpi.class.php(482): PluginArchiswSwcomponent_Item::displayTabContentForItem(Object(Project), '1', '') #2 /var/www/glpi/ajax/common.tabs.php(96): CommonGLPI::displayStandardTab(Object(Project), 'PluginArchiswSw...', '', Array) #3 {main} thrown in /var/www/glpi/plugins/archisw/inc/swcomponent_item.class.php on line 435

**Comment by ericferon** [comment]
Solved in v2.0.7
