### ISSUE TITLE
BUG : Type Appli

### ISSUE THREAD

**Issue by EC2311** [ericferon/glpi-archisw#13]
Hello
- The field is filled in table, but when editing the appli, it is blank on the screen

**Comment by ericferon** [comment]
Unclear.
Do you mean that the name entered in the table Dropdown->Apps structure->Types does not appear in the field "Type" of an  application ?

**Comment by EC2311** [comment]
Hello

When editing an appli, the type of the appli doesn't appear in the field although it appears on the selectionnable screen (in the list of appli, fi)

**Comment by ericferon** [comment]
Sorry, I cannot reproduce your problem

**Comment by EC2311** [comment]
Hello

Using Chrome : 
In the list of the applications:
![image](https://user-images.githubusercontent.com/42341169/45672252-f991ca00-bb27-11e8-858c-108e41d1d110.png)
The type appears

and when editing this application : 
![image](https://user-images.githubusercontent.com/42341169/45672322-280fa500-bb28-11e8-94dd-d40d8ecfae71.png)
The type is empty

Best regards

**Comment by ericferon** [comment]
I see, but I cannot reproduce this behaviour.
I can just explain how my types are defined.
In the dropdown table "Types", my types are created in the 'root' entity with 'visibility' set to 'yes'.
I have several types, organized in several groups (that is some types are children of other ones, in a tree structure with 2 levels)
![image](https://user-images.githubusercontent.com/8736398/45999682-a4653380-c0a6-11e8-816f-ed60d4c7091d.png)
Best regards,

**Comment by EC2311** [comment]
Hello

Just for Information : 
solved, but I don't know how !

Thanks
And a very good job !

**Comment by ericferon** [comment]
Fine !
