### ISSUE TITLE
enhancement request : Add role to database/WebApp

### ISSUE THREAD

**Issue by lixp99** [ericferon/glpi-archisw#20]
Hi,
Thanks for plugin
Is there a way to add a role (dev/prod/...), same as computer, to a database and webapplication?
regards

**Comment by ericferon** [comment]
Yes, you have to add entries in the table "Link roles" under "Apps structures", via the menu "Setup->Dropdowns".

The "type" must contain the PHP class name, f.i PluginDatabasesDatabase or PluginWebapplicationsWebapplication, that you can find, in the "inc" directory of the targeted plugin, in the main "inc.php" file.

Best regards,
