### ISSUE TITLE
List Name of structure appli in FormCreator

### ISSUE THREAD

**Issue by EC2311** [ericferon/glpi-archisw#21]
Hello

How to populate structureAppli in Formcreator ?

I tryed to add 
//PluginArchiswSwcomponent::class  => PluginArchiswSwcomponent::getTypeName(2)], 
in showform() function in question.class.php 

but it doesn't run

For Database pluging I added
PluginDatabasesDatabase::class              => PluginDatabasesDatabase::getTypeName(2),
and it runs

Thanks
Best regards

**Comment by ericferon** [comment]
I don't know : I'm not using Formcreator.
Pay attention, maybe, to the fact that getTypeName(2) will return a string of 2 words separated by a space (i.e, "Apps Structures"). 
Best regards,
