### ISSUE TITLE
Attached items

### ISSUE THREAD

**Issue by EC2311** [ericferon/glpi-archisw#22]
Hello

Would it be possible to add "attached items" to the list of fields visible?
![image](https://user-images.githubusercontent.com/42341169/53028883-0b292600-3468-11e9-9380-4046a4d9081a.png)
there with the key?

Thanks

**Comment by ericferon** [comment]
It's possible : you may add the field "Associated items" to the list of visible fields.
You will then get the key and the (clickable) name of all the associated items.
Best regards,

**Comment by EC2311** [comment]
I'm very sorry, but when I look using the key : 
here are the fields I may add : 
![image](https://user-images.githubusercontent.com/42341169/54123518-47fd9280-4400-11e9-8c60-39304ed1bd47.png)
![image](https://user-images.githubusercontent.com/42341169/54123549-577cdb80-4400-11e9-9f63-78be79f63817.png)
![image](https://user-images.githubusercontent.com/42341169/54123572-64013400-4400-11e9-901c-8db9fbf3fcad.png)
![image](https://user-images.githubusercontent.com/42341169/54123593-70858c80-4400-11e9-8fa1-70a4472d26e9.png)

I don't see 'associated items' so I can't see the items associated :(

**Comment by ericferon** [comment]
"Associated items/Eléments rattachés" lays between "Component owner/Propriétaire du Composant" and "Associable to a ticket/Associable à un ticket" in my GLPI v9.2.1 instance, using v2.0.17 of the plugin.
Best regards,

**Comment by EC2311** [comment]
I switched language into english instead of french (just in case of)

and here is what I see : 
![image](https://user-images.githubusercontent.com/42341169/54194807-62497600-44bd-11e9-94e3-e781097454eb.png)


I am in GLPI 9.3.2 and plugin 2.017

how does your screen look like ?

**Comment by ericferon** [comment]
As this :
![Screenshot_20190313_105624](https://user-images.githubusercontent.com/8736398/54270118-f2032900-457e-11e9-9768-cbdbfb75008c.png)
I will look whether it's due to the GLPI version.
Best regards,

**Comment by EC2311** [comment]
In the same time : 
Have a look in the title of the windows of items to show : it is written "Cpps structures ID" and not "Apps Structures" : mismatch in traduction ? I have poedit.exi, but I didn't find the term Cpps anywhere in any file of report...

**Comment by ericferon** [comment]
There was indeed a bug for GLPI v9.3.
This is solved in v2.0.18.
Best regards,
