### ISSUE TITLE
Class 'PluginArchiswSwcomponent' not found

### ISSUE THREAD

**Issue by peteredhair** [ericferon/glpi-archisw#23]
On GLPI 9.4 when i install the plugin there is an error in the apache errolog file and the list of plugins disappears.

The error found in apache error log is the following:

PHP Fatal error:  Uncaught Error: Class 'PluginArchiswSwcomponent' not found in /var/www/html/glpi/plugins/archisw/hook.php:334\nStack trace:\n#0 /var/www/html/glpi/inc/plugin.class.php(1115): plugin_archisw_MassiveActions('Plugin')\n#1 /var/www/html/glpi/inc/massiveaction.class.php(577): Plugin::doOneHook('archisw', 'plugin_archisw_...', 'Plugin')\n#2 /var/www/html/glpi/inc/search.class.php(1587): MassiveAction::getAllMassiveActions(Object(Plugin), 0)\n#3 /var/www/html/glpi/inc/search.class.php(99): Search::displayData(Array)\n#4 /var/www/html/glpi/inc/search.class.php(80): Search::showList('Plugin', Array)\n#5 /var/www/html/glpi/front/plugin.php(44): Search::show('Plugin')\n#6 {main}\n  thrown in /var/www/html/glpi/plugins/archisw/hook.php on line 334, referer: http://glpi.besseguros.pt/front/plugin.ph

The same error occurs in dataflows.

Congrats on the this great plugin.

**Comment by ericferon** [comment]
The plugin is not yet compatible with v9.4.
It's planned in May 2019, if I have time.
Best regards,

**Comment by peteredhair** [comment]
Thanks

Cumprimentos,
Pedro Ruivo
Enviado do meu iPad

No dia 03/04/2019, às 14:46, Eric Feron <notifications@github.com> escreveu:
