### ISSUE TITLE
Sort List of application 'child of' 

### ISSUE THREAD

**Issue by EC2311** [ericferon/glpi-archisw#24]
Hello

When filling an application with 'Enfant de' (Child of) : How is sorted the list of application we can see ?
Perhaps to sort using alphabetical order should be better ?

Thanks
Best regards

**Comment by ericferon** [comment]
Applications are listed hierarchically by entity, then by application name inside each entity, then by child name recursively.
Best regards,

**Comment by EC2311** [comment]
Hello

Just a feedback : 
- No different entity level : just one entity : root.
In fact I created the application using insert into statement, migrated from appliance plugin. OK

But I forgot to fill 'completename' field
Extract of the statement : 
INSERT IGNORE INTO `glpi_plugin_archisw_swcomponents` ( `name` , `comment` , `locations_id` , `plugin_archisw_swcomponenttypes_id`, `plugin_archisw_swcomponentstates_id`, users_id, groups_id) 

by filling completename (=name), then it's ok
