### ISSUE TITLE
Updating Computer (and others?) items associated

### ISSUE THREAD

**Issue by EC2311** [ericferon/glpi-archisw#25]
How Can we update the role (Prod, dev...) of a computer already assigned ?
Is the only way is to remove and assign it again ?
Would it be possibile to update the fields with Action?

Thanks

**Comment by ericferon** [comment]
Unfortunately, yes : you have to remove and then add again the link.
The GLPI core does not provide the ability to modify an associated item.
Best regards,

**Comment by EC2311** [comment]
Hello
Thanks for feed back.
But as role of server (dev, prod etc) is a topic part of server information, would it be possible to retrieve (and list) this information from server part in the list of fields shown ?
Rather to have 2 places with possibility of having 2 different informations for the server (the first in computer fields, the other in structure application fields?) In your case, it may possible to have a computer role as 'Dev' in structure application, and for the same computer it may be set up as Prod in GLPI part., no?

Best regards

**Comment by ericferon** [comment]
You can associate other items than servers. So, your proposal should be valid for these other kinds of items too.
And even for servers, you could have non-prod servers hosting a Dev and a QA application instances. In this case, you need to qualify differently the link to a same server.
But I understand that in your specific case, if the server is already identified as Dev or Prod, it's annoying to enter it twice. But I don't see how to get a general solution.
Best regards,
