### ISSUE TITLE
Add link to contract ?

### ISSUE THREAD

**Issue by prizand** [ericferon/glpi-archisw#26]
Would it be possible to link this object to contracts ?
Thanks !

**Comment by ericferon** [comment]
If seems feasible. I will add this capability to the next version (coming in the next days).
Best regards,

**Comment by prizand** [comment]
Great, thank you !

**Comment by ericferon** [comment]
Done in v2.1.1.
Best regards,

**Comment by prizand** [comment]
Thanks !
