### ISSUE TITLE
GLPI 9.4.3 - Archisw 2.1.2 - Bug displaying attached items

### ISSUE THREAD

**Issue by EC2311** [ericferon/glpi-archisw#33]
Hello

In main screen, when adding attached items, we see the ID of items and not the its name

![image](https://user-images.githubusercontent.com/42341169/62633963-54e1cc00-b935-11e9-874e-85eeb7d169de.png)

The type of items is not shown neither

**Comment by ericferon** [comment]
Thanks for reporting this bug.
It has been solved in V2.1.3.
Best regards,
