### ISSUE TITLE
Not a problem : but 'how to'

### ISSUE THREAD

**Issue by EC2311** [ericferon/glpi-archisw#35]
Hello,

I use an other plugin (applications web) joined to yours (which runs very good for us)
I would like to add 'applications web' linked with project (like you did for structure appli)
I posted on the plugin team, but since may 2019, no feed back...

I am sure it's not so hard to do the link between 'applications web' and 'project' but I don't know how to do it.

Could you help me ?

Thanks

**Comment by ericferon** [comment]
You have to modify the code of inc/webapplication.class.php, and add "Project" in the $types variable (line 43).
You will have to repeat this each time that there is a new plugin version.
As "archisw" is based initially on "webapplication", and extends it, you could also move your "webapplication" inventory in "archisw".
Best regards,
