### ISSUE TITLE
Bug : Nom dans Application

### ISSUE THREAD

**Issue by EC2311** [ericferon/glpi-archisw#36]
Bonjour

j'essaie de renommer le nom d'une application.
Dans l'historique on voit bien que le nom de l'application a été modifié.

Mais l'ancien nom reste 'visible' , y compris dans les projets.
En regardant dans la DB : 
A priori seul le nom complet (completename) est modifié et pas le nom 'court' (name)

**Comment by ericferon** [comment]
Je ne parviens pas à reproduire votre problème : chez moi, "name" et "completename" sont tous 2 modifiés.
Bien cordialement,

**Comment by EC2311** [comment]
j'ai trouvé (et désolé)
un enregistreement identique (nom court) existait dans la table mais il etait supprimé (corbeille)
en le supprimant -> cela fonctionne. pas de souci

Désolé
