### ISSUE TITLE
EVO : Lien avec Fournisseur

### ISSUE THREAD

**Issue by EC2311** [ericferon/glpi-archisw#39]
Bonjour

En souhaitant utiliser la partie fournisseur de GLPI, je vois que l'on peut faire lien avec Database et web-applications , mais pas avec Structure d'appli... 
Pourtant dans la variable 'type' des 2 plugins je ne vois pas la notion de fournisseur...

Comment cela fonctionne t-il ?

Est-il possible de faire le lien entre structure d'appli et fournisseur ?

merci

**Comment by redfish8** [comment]
Bonjour,
J'imagine que c'est en cours car je vois Apps Structure depuis les fournisseurs mais ne peut pas créer de lien. Est-ce prévu prochainement ?
