### ISSUE TITLE
Missing DB

### ISSUE THREAD

**Issue by bacus99** [ericferon/glpi-archisw#41]
Hi, 

Found issue after fresh install

****PHP Notice (8): Undefined index: plugin_archisw_standards_id in /var/www/html/glpi/plugins/archisw/inc/swcomponent.class.php at line 384
SQL Error "1146": Table 'dev_glpi.glpi_plugin_archisw_standards' doesn't exist in query "SHOW COLUMNS FROM `glpi_plugin_archisw_standards`"

**Comment by bacus99** [comment]
Solution:
Create manually
-- -----------------------------------------------------
-- Table `glpi_plugin_archisw_standards`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `glpi_plugin_archisw_standards`;
CREATE  TABLE `glpi_plugin_archisw_standards` (
  `id` INT(11) NOT NULL AUTO_INCREMENT ,
  `name` VARCHAR(45) NOT NULL ,
  `comment` VARCHAR(45) NULL ,
  PRIMARY KEY (`id`) ,
  UNIQUE INDEX `plugin_archisw_standards_name` (`name` ASC) )
 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

INSERT INTO `glpi_plugin_archisw_standards` ( `id` , `name` , `comment` )  VALUES (1,'Standard','Standard');
INSERT INTO `glpi_plugin_archisw_standards` ( `id` , `name` , `comment` )  VALUES (2,'Non-Standard','Non-Standard');
INSERT INTO `glpi_plugin_archisw_standards` ( `id` , `name` , `comment` )  VALUES (3,'Proposed Standard','Proposed Standard');
INSERT INTO `glpi_plugin_archisw_standards` ( `id` , `name` , `comment` )  VALUES (4,'Provisional Standard','Provisional Standard');
INSERT INTO `glpi_plugin_archisw_standards` ( `id` , `name` , `comment` )  VALUES (5,'Phasing-Out Standard','Phasing-Out Standard');
INSERT INTO `glpi_plugin_archisw_standards` ( `id` , `name` , `comment` )  VALUES (6,'Retired Standard','Retired Standard');


Add to glpi_plugin_archisw_swcomponents manually
`plugin_archisw_standards_id` INT(11) NOT NULL default '0' COMMENT 'Standard status (Standard, Not standard, ...)'

**Comment by ericferon** [comment]
These SQL statements are present in the empty.sql file.
So, this table is normally created.
K.r,
