### ISSUE TITLE
Uncaught Exception TypeError: Argument 1 passed to Dropdown

### ISSUE THREAD

**Issue by bacus99** [ericferon/glpi-archisw#42]
GLPI V. 9.5.1

Uncaught Exception TypeError: Argument 1 passed to Dropdown::addNewCondition() must be of the type array, string given, called in /var/www/html/glpi/inc/dropdown.class.php on line 157 in /var/www/html/glpi/inc/dropdown.class.php at line 278

When I go to Computer / App Structures TAB / I have this error
![image](https://user-images.githubusercontent.com/11425241/91882928-b1efa480-ec51-11ea-82e8-5f6f18177760.png)

I can assign from Apps Structures but not from the computer
![image](https://user-images.githubusercontent.com/11425241/91882977-c16eed80-ec51-11ea-8b94-802ff813d24b.png)

**Comment by ericferon** [comment]
Thank you for submitting this bug report.
It has been solved in v2.2.1.
K.r,
