### ISSUE TITLE
Uncaught Exception Error: Call to undefined method PluginWebapplicationsWebapplication::registerType()

### ISSUE THREAD

**Issue by jcervantes-sipecom** [ericferon/glpi-archisw#43]
Hi, I already install the plugin but I'm getting the followin error on Debug mode when trying to Activate it:

> Uncaught Exception Error: Call to undefined method PluginWebapplicationsWebapplication::registerType() in /usr/share/g952/archisw/setup.php at line 63

My GLPI is for testing: GLPI 9.5.2 
Plugin version: v2.2.1
SO: Ubuntu 20.04.1 LTS

Also, I'm using the Filesystem Hirerarchie Standard for Ubuntu:

> https://glpi-developer-documentation.readthedocs.io/en/master/packaging.html
> https://glpi-install.readthedocs.io/en/latest/install/index.html#files-and-directories-locations

**Comment by ericferon** [comment]
You probably didn't install the Webapplication plugin.
There is no impact on the plugin functionality, normally.
K.r,

**Comment by jcervantes-sipecom** [comment]
Hi Yes, but this error avoids the plugins page load, if it was not in debug mode, the error could not be displayed, the page is completely blank.

Also the Webapplication plugin is installed and active:
![image](https://user-images.githubusercontent.com/56606032/96505302-8c2b5880-121b-11eb-94e9-4a9de6634caf.png)

I had to move the archisw folder to another location to be able to load the plugins page and once I verified the Webapplication plugin is installed and activated, I moved the archisw folder back to the plugins folder. But the error persist:

![image](https://user-images.githubusercontent.com/56606032/96505763-386d3f00-121c-11eb-84f8-1509e7a4f396.png)

If the Webapplications plugin is necessary then it should be added in the **setup.php** which is required, like this:

> 'requirements' => [
>          'glpi' => [
>             'min' => '9.5',
>             'dev' => false,
>              **'plugins' => [
>                'webapplications',
>             ],**

Additionally, on line 63 specify that the Webapplications plugin must be activated. I solved it like this:

> $ plugin = new Plugin ();
> if (class_exists ($itemtype) && $plugin-> isActivated ($ itemtype)) {

Attach my setup.php ([setup.php.txt](https://github.com/ericferon/glpi-archisw/files/5404397/setup.php.txt))

In this way I could load the plugin page when:

- The Webapplication is not installed or installed but not active:
![image](https://user-images.githubusercontent.com/56606032/96506198-db25bd80-121c-11eb-906d-d3b4f0cd3642.png)

- The Webapplication is installed and active:
![image](https://user-images.githubusercontent.com/56606032/96506611-8d5d8500-121d-11eb-99e1-96d984d83319.png)

**Comment by ericferon** [comment]
In fact, the plugin Webapplication is now integrated into GLPI core, as appliance.
So, the "registerType" method doesn't exist anymore for Webapplication.
In order to avoid the error message, you should modify the line 58 into a comment : // 'PluginWebapplicationsWebapplication',
Can you confirm that this is a solution for you ?
I will then release a new version of the plugin.
Thank you for your contribution,

**Comment by jcervantes-sipecom** [comment]
Yes, the problem doesn't show it anymore when installing the plugin.
