### ISSUE TITLE
Evo : Ajout de Typologies à l'application

### ISSUE THREAD

**Issue by EC2311** [ericferon/glpi-archisw#44]
Bonjour

Serait-il possible d'ajouter les types d'informations ci-dessous : 
- Obsolescence de l'application : Valeur à définir par nos soins (Intitulés) 
Ex : 0, 1, 2 ou 3 sont des types d'obsolescence

- Evolutivité de l'application : Valeur à définir par nos soins (Intitulés)
Ex : 0, 1, 2 ou 3 sont des types d'évolutivité

- Compétence : Valeur à définir par nos soins (Intitulés)
Ex : 0, 1, 2 ou 3 sont des types de compétence

- Fiabilité de l'application : Valeur à définir par nos soins (Intitulés)
Ex : 0, 1, 2 ou 3 sont des types de fiabilité

- Pondération de la compétence : Valeur à définir par nos soins (Intitulés)
Ex : 0, 1, 2 ou 3 sont des types de pondération.

Merci

**Comment by ericferon** [comment]
Bonjour,
Oui, j'ai déjà songé ajouter des critères d'évaluation d'une application, dans un onglet supplémentaire pour ne pas surcharger l'écran principal.
Pouvez-vous expliquer ce que vous entendez par "compétence" et "pondération de la compétence", pour une application ou un composant applicatif ?
J'essaierai ensuite de placer ce développement dans ma charge de travail.
Bien cordialement,

**Comment by EC2311** [comment]
Competence : Capacité à connaitre l'application.
Ponderation : delai/projet pour la maitriser.

De manière générale, pourrait-on envisager des criteres souples/modifiables ? 
Afin d'éviter un ajout massif d'indicateur faire peut etre un style comme le plugin 'fields' champs supplémentaires ?
mais à mon avis ceci doit etre certainement plus difficile à mettre en œuvre...

**Comment by ericferon** [comment]
La v3.0.0 permet d'ajouter/supprimer des champs par rapport au standard.
Bien cordialement,
