### ISSUE TITLE
Type ordinateurs

### ISSUE THREAD

**Issue by EC2311** [ericferon/glpi-archisw#45]
Bonjour
Quand on ajoute un ordinateur, on a un type d'ordi (Dev, PROD etc)
Ou se trouve ces types d'ordinateur ? pas d'intitulés ?
COmment les modifier ?

Merci

**Comment by ericferon** [comment]
Cette liste est gérée via le menu SetUp->Dropdowns, section Apps Structures, table Link Roles.
Bien cordialement,
