### ISSUE TITLE
BUG ? GLPI 9.5.3 / ARCHISW 221

### ISSUE THREAD

**Issue by EC2311** [ericferon/glpi-archisw#46]
Bonjour 
Quelques remarques suite migration de 9.3.1 en 9.5.3 (dev)

- souci en ligne 63 du setup.php
![image](https://user-images.githubusercontent.com/42341169/106175960-01051b80-6197-11eb-809c-c84330a74cc8.png)

J'ai plugin web, db et archisw en place.
Je suis obligé de mettre en commentaire sinon la liste des plugins ne s'affiche pas.
A priori lié aux recherches de vue sauvegardée : en supprimant la vue sauvegardée, l'accés est ok.

- dans la liste des applications
 en mode debug de GLPI
PHP User deprecated function (16384): Use DBmysql::fetchAssoc() in *\wwwroot\inc\toolbox.class.php at line 634
(peut etre une bonne 50 de lignes ainsi), puis on a ensuite la liste des applications...
Backtrace :
  inc\toolbox.class.php:634                          trigger_error()
  inc\dbmysql.class.php:485                          Toolbox::deprecated()
  plugins\archisw\hook.php:301                       DBmysql->fetch_assoc()
  inc\plugin.class.php:1431                          plugin_archisw_giveItem()
  inc\search.class.php:5512                          Plugin::doOneHook()
  inc\search.class.php:1452                          Search::giveItem()
  inc\search.class.php:320                           Search::constructData()
  inc\search.class.php:95                            Search::getDatas()
  inc\search.class.php:80                            Search::showList()
  plugins\archisw\front\swcomponent.php:34           Search::show()

mais je pense que cette erreur est commune à GLPI et non archisw...

d'autre part, je me pose la question sur le plugin 'web-application' sachant qu'il est integré dans le coeur de GLPI...(applicatifs). ce serait maintenant 'applicatifs' de 'gestion' qu'il faudrait relier.

Ensuite lors d'utilsiation de filtre (sur propriétaire), la valeur n'est pas chargée
![image](https://user-images.githubusercontent.com/42341169/106296328-cdd39280-6251-11eb-9444-907c0014e80b.png)

**Comment by ericferon** [comment]
Concernant le 1er point, une correction n'avait pas encore été publiée (depuis longtemps :-(
Il suffit de commenter la ligne 58, qui est le seul plugin posant problème.
Cela est résolu dans la version 2.2.2.
L'autre message d'erreur est effectivement indépendant de ma volonté.
Bien cordialement,

**Comment by EC2311** [comment]
Bonjour

OK pour le retrait du plugin webapplication. Mais... sachant que les données issues du plugin sont integrés dans le coeur de GLPI en tant que table 'GLPI_appliances' : comment faire le lien ? on remplace directement le nom du plugin par 'applia ces' ?

**Comment by EC2311** [comment]
et concernant le bug (?) sur la selection avec 'propriétaire composant' ?
![image](https://user-images.githubusercontent.com/42341169/106758897-5bd4c200-6632-11eb-94d3-901acecf0322.png)

Merci

**Comment by EC2311** [comment]
Possibilité de pouvoir 'voir' l'element attaché 'applicatif' comme champ paramétrable (via la clé) dans la liste des applis ?

**Comment by ericferon** [comment]
Le bug "propriétaire du composant" est corrigé en v2.2.4.
"Appliance" a également été ajouté, puisque ce n'est plus un plugin.
Bien cordialement,

**Comment by EC2311** [comment]
Bonjour
Merci bien 

Pour information : 
En refaisant des tests de mise  jour du plugin, (reprise des données anciennes versions via un dump sql, afin de faire la reconversion plugin) les données de la table principale ne sont pas reprise integralement suite probleme de date. Je m'en suis sorti en ajoutant un ignore dans l'instruction. Je pense que cela doit etre du ^une différence 'coding' lros de la creation table/mise à joru des données ?

Néanmoins
le champ propriétaire est ok.

mais j'ai toujours les problemes de fonction deprecated.(en debug ou sans position debug)
![image](https://user-images.githubusercontent.com/42341169/107052251-b6565580-67cd-11eb-920e-d455041d8613.png)

**Comment by ericferon** [comment]
OK, merci pour l'info.
La fonction fetch_assoc a été remplacée dans la version 2.2.5
