### ISSUE TITLE
Liaison avec Ticket ?

### ISSUE THREAD

**Issue by EC2311** [ericferon/glpi-archisw#49]
Bonjour,

Dans la structure d'appli, nous avons ceci comme onglet
![image](https://user-images.githubusercontent.com/42341169/108331935-8cd6fa00-71cf-11eb-97b8-126d760ccb5e.png)

comment associer un Ticket (demande/incident?) à la structure d'appli ?
Ce ticket pouvant etre généré par FormCreator (demande de travail sur une appli à creer (n'existe pas dans GLPI) ou existance (existe dans GLPI)

Merci

**Comment by ericferon** [comment]
Dans le profil associé à votre utilisateur, dans l'onglet "Assistance", vous devez ajouter "Apps Structure" dans la liste du champ "Associable avec un ticket".
Bien cordialement,
