### ISSUE TITLE
Plugin statecheck required for archisw ?

### ISSUE THREAD

**Issue by EC2311** [ericferon/glpi-archisw#5]
I think the statecheck plugin is required before implementing this plugin ?
And installaing the statecheck pluging requires updating in GLPI  itself...

would it be possible (or perhaps it's possible but I didn't find the way) to install archisw without statecheck ?

Thanks
Best regards

**Comment by ericferon** [comment]
The statecheck plugin is not required for any other plugin.
Best regards,

**Comment by ericferon** [comment]
I confirm that statecheck is not required.
The error is due to an unnecessary test, that I removed in the last commit.
Best regards,
