### ISSUE TITLE
Uncaught Exception Error: Call to undefined method PluginArchiswSwcomponent::dropdownDataflow() 

### ISSUE THREAD

**Issue by elmotofan** [ericferon/glpi-archisw#50]
GLPI v. 9.5.3
When you go to **Inventory/Computers**, select more than one item, and try to **associate to the App structure** by massive actions, you get an error:
**Uncaught Exception Error: Call to undefined method PluginArchiswSwcomponent::dropdownDataflow() in /var/www/html/servicedesk/plugins/archisw/inc/swcomponent.class.php at line 771**

![image](https://user-images.githubusercontent.com/57363519/129988536-c3cbc0a2-79c1-4b09-9923-d6ed9ae0f517.png)

Thank you for this great plugin.

**Comment by ericferon** [comment]
Thank you for reporting this bug.
It has been fixed in v2.2.6
K.r,
