### ISSUE TITLE
erreur > actions > clôner

### ISSUE THREAD

**Issue by JC-os** [ericferon/glpi-archisw#51]
Bonjour et merci pour vôtre plug-in.
Ayant beaucoup d'applications à mettre dans l'inventaire j'ai voulu utiliser la fonction de modification de masse:  actions > clôner.
Malheureusement cela ne marche pas et Glpi m'envoie cette erreur: 
```
Opération échouée
(0 problèmes de droits, 1 échecs)
BatchAmiat : Erreur en exécutant l'action
```
Est-il possible qu'il s'agisse d'un bug?
Merci pour vôtre plugin!

**Comment by ericferon** [comment]
Bonjour,
L'action de clôner est proposée en standard par GLPI, et n'est pas adaptée au plugin : lors du clonage, tous les champs sont copiés tels quels et sont associés à un nouvel identifiant. Donc sans changement de nom. Or un index dans la base de données s'assure que le nom est unique sous un noeud d'une structure applicative. D'où le message d'erreur.
Plus bas dans la liste d'actions en masse, vous avez la possibilité de "dupliquer". Cette action a été ajoutée par le plugin et évite le problème décrit ci-dessus en ajoutant " (Copy 1)" (ou plus) au nom.

**Comment by JC-os** [comment]
Merci beaucoup, "dupliquer" fonctionne parfaitement!
