### ISSUE TITLE
Compatibility with 10.x

### ISSUE THREAD

**Issue by derry43** [ericferon/glpi-archisw#52]
Is archisw compatible with 10.x and if not, do you intend to work on this?

**Comment by derry43** [comment]
I think that the comment for the 2.2.9 release should indicate that the release is also compatible with 10.0.x. I have tested with GLPI 10.0.0-rc3 and it appears to work fine.

**Comment by ericferon** [comment]
Yes, all my published plugins are now compatible with version 10.x.
I will adapt the release headlines.
K.r,
