### ISSUE TITLE
Тo new instances are created

### ISSUE THREAD

**Issue by akupovih** [ericferon/glpi-archisw#53]
GLPI:  ver. 10.0.0
Apps structures: ver. 2.2.9
PHP:  ver. 7.4.13

I've installed and enabled  the plugin Apps structures via marketplace and am now trying to create item.
And when I push the button Add nothing happens.
In the error log I've found exceptions:

`FastCGI sent in stderr: "PHP message: PHP Deprecated:  Autocompletion feature has been removed. in /var/www/html/glpi10.0.0/src/Toolbox.php on line 543PHP message: PHP Deprecated:  Autocompletion feature has been removed. in /var/www/html/glpi10.0.0/src/Toolbox.php on line 543PHP message: PHP Deprecated:  Autocompletion feature has been removed. in /var/www/html/glpi10.0.0/src/Toolbox.php on line 543" while reading response header from upstream, client: 192.168.1.208, server: glpi.domain, request: "GET /ajax/common.tabs.php?_target=/marketplace/archisw/front/swcomponent.form.php&_itemtype=PluginArchiswSwcomponent&_glpi_tab=PluginArchiswSwcomponent$main&id=&withtemplate= HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm/php-fpm.sock:", host: "glpi.domain", referrer: "https://glpi.domain/marketplace/archisw/front/swcomponent.form.php"`

`FastCGI sent in stderr: "PHP message: PHP Deprecated:  Autocompletion feature has been removed. in /var/www/html/glpi10.0.0/src/Toolbox.php on line 543PHP message: PHP Deprecated:  Autocompletion feature has been removed. in /var/www/html/glpi10.0.0/src/Toolbox.php on line 543" while reading upstream, client: 192.168.1.208, server: glpi.domain, request: "GET /ajax/common.tabs.php?_target=/marketplace/archisw/front/swcomponent.form.php&_itemtype=PluginArchiswSwcomponent&_glpi_tab=PluginArchiswSwcomponent$main&id=&withtemplate= HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm/php-fpm.sock:", host: "glpi.domain", referrer: "https://glpi.domain/marketplace/archisw/front/swcomponent.form.php"`

`FastCGI sent in stderr: "PHP message: PHP Deprecated:  Autocompletion feature has been removed. in /var/www/html/glpi10.0.0/src/Toolbox.php on line 543PHP message: PHP Deprecated:  Autocompletion feature has been removed. in /var/www/html/glpi10.0.0/src/Toolbox.php on line 543PHP message: PHP Deprecated:  Autocompletion feature has been removed. in /var/www/html/glpi10.0.0/src/Toolbox.php on line 543PHP message: PHP Deprecated:  Autocompletion feature has been removed. in /var/www/html/glpi10.0.0/src/Toolbox.php on line 543" while reading upstream, client: 192.168.1.208, server: glpi.domain, request: "GET /ajax/common.tabs.php?_target=/marketplace/archisw/front/swcomponent.form.php&_itemtype=PluginArchiswSwcomponent&_glpi_tab=PluginArchiswSwcomponent$main&id=&withtemplate= HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm/php-fpm.sock:", host: "glpi.domain", referrer: "https://glpi.domain/marketplace/archisw/front/swcomponent.form.php"
`

![error](https://user-images.githubusercontent.com/36922467/169002841-860cd677-9d2a-4aad-84c9-9da0f1ab980c.png)

**Comment by ericferon** [comment]
I cannot reproduce this behaviour in GLPI 10.
Probably solved with the new GLPI core version.
K.r,
