### ISSUE TITLE
Messages of Deprecated features on Toolbox

### ISSUE THREAD

**Issue by gam04** [ericferon/glpi-archisw#54]
Can i disable these messages?

<img width="824" alt="image" src="https://user-images.githubusercontent.com/47505661/172079411-d8db18a5-12ed-4d8b-a9d4-384a7e8fad38.png">

**Comment by bacus99** [comment]
You can disable for now the DEBUG MODE to hide the messsage.  About correction, I don't know the answer

**Comment by ericferon** [comment]
See issue #53
