### ISSUE TITLE
Adding new app in Glpi 10.0.2

### ISSUE THREAD

**Issue by JC-os** [ericferon/glpi-archisw#55]
Hello,
First of all, thank you for your software.
I've upgraded to glpi 10.0.2, and your plugin Apps structures v. 2.2.9 just seems to work fine.

I've just discovered that adding a new Apps Structure (/marketplace/archisw/front/swcomponent.form.php) is not saving the data in the db.

Luckily I could go into one existing app anc action/duplicate it so this is an acceptable (to me) workaround,

Best regards,
Joseph

**Comment by ericferon** [comment]
Indeed.
It seems that the "Status Startdate" is not filled anymore by a default value and this behaviour triggers an SQL error.
I will solve this problem in a new version.
In the meantime, you solve the problem if you enter a value in this field.
K.r,
