### ISSUE TITLE
Effacement impossible 

### ISSUE THREAD

**Issue by redfish8** [ericferon/glpi-archisw#56]
Bonjour,
J'ai essayé avec deux version  différentes 2.2.12 et 2.2.9, je n'arrive pas à effacer un objet "App structure", j'ai essayé de supprimer tous les liens de l'objet mais que je clique sur "Put in trashbin" dans l'objet ou par "Action" depuis la liste, une page blanche plugins/archisw/front/swcomponent.form.php est systématiquement présentée.
Dans php-errors.log je trouve :

`
[2022-11-08 14:34:20] glpiphplog.CRITICAL:   *** Uncaught Exception Error: Call to undefined method Toolbox::useCache() in /var/www/glpi/plugins/archisw/inc/swcomponent.class.php at line 52
  Backtrace :
  src/CommonDBTM.php:2031                            PluginArchiswSwcomponent->pre_deleteItem()
  plugins/archisw/front/swcomponent.form.php:56      CommonDBTM->delete()
  
[2022-11-08 14:34:32] glpiphplog.CRITICAL:   *** Uncaught Exception Error: Call to undefined method Toolbox::useCache() in /var/www/glpi/plugins/archisw/inc/swcomponent.class.php at line 52
  Backtrace :
  src/CommonDBTM.php:2031                            PluginArchiswSwcomponent->pre_deleteItem()
  src/MassiveAction.php:1423                         CommonDBTM->delete()
  src/MassiveAction.php:1404                         MassiveAction::processMassiveActionsForOneItemtype()
  src/MassiveAction.php:1382                         MassiveAction->processForSeveralItemtypes()
  front/massiveaction.php:59                         MassiveAction->process()
`
Est-ce spécifique à mon (mes) setup ?

Merci

Patrick

**Comment by ericferon** [comment]
Bonjour,
Ce bug a été corrigé dans la version 2.2.13.
Bien cordialement,
