### ISSUE TITLE
missing table

### ISSUE THREAD

**Issue by we-sell-bags** [ericferon/glpi-archisw#57]
Version: 2.2.14
GLPI 10.0.5

loaded the plugin "in" enabled it
but when i go to the tab

"assets"->"app structures"

Table 'glpi.glpi_plugin_archisw_swcomponents' doesn't exist

**Comment by ericferon** [comment]
Hi,
Have you an error message in the sql error log (files/_log/sql-errors.log) ?
K.r,

**Comment by we-sell-bags** [comment]
`  marketplace/archisw/front/swcomponent.php:34       Search::show()
  {"user":"9@glpi","mem_usage":"0.001\", 11.47Mio)"} 
[2022-11-15 12:42:36] glpisqllog.ERROR: DBmysql::query() in /usr/share/glpi/src/DBmysql.php line 370
  *** MySQL query error:
  SQL: SELECT DISTINCT `glpi_plugin_archisw_swcomponents`.`id` AS id, 'the.user' AS currentuser,
                         `glpi_plugin_archisw_swcomponents`.`name` AS `ITEM_PluginArchiswSwcomponent_1`,
                        `glpi_plugin_archisw_swcomponents`.`id` AS `ITEM_PluginArchiswSwcomponent_1_id` FROM `glpi_plugin_archisw_swcomponents` ORDER BY `ITEM_PluginArchiswSwcomponent_1` ASC  LIMIT 0, 20
  Error: Table 'glpi.glpi_plugin_archisw_swcomponents' doesn't exist
  Backtrace :
  src/Search.php:1441                                
  src/Search.php:447                                 Search::constructData()
  src/Search.php:199                                 Search::getDatas()
  src/Search.php:176                                 Search::showList()
  marketplace/archisw/front/swcomponent.php:34       Search::show()
  {"user":"9@glpi","mem_usage":"0.000\", 11.47Mio)"} 
[2022-11-15 12:51:40] glpisqllog.ERROR: DBmysql::query() in /usr/share/glpi/src/DBmysql.php line 370
  *** MySQL query error:
  SQL: SHOW COLUMNS FROM `glpi_plugin_archisw_swcomponents`
  Error: Table 'glpi.glpi_plugin_archisw_swcomponents' doesn't exist
  Backtrace :
  src/DBmysql.php:889                                
  src/CommonDBTM.php:611                             DBmysql->listFields()
  src/CommonDBTM.php:3113                            CommonDBTM->getEmpty()
  marketplace/tag/hook.php:75                        CommonDBTM->isEntityAssign()
  src/Plugin.php:1799                                plugin_tag_getAddSearchOptionsNew()
  src/Search.php:7969                                Plugin::getAddSearchOptionsNew()
  src/Search.php:7656                                Search::getOptions()
  src/Search.php:2749                                Search::getCleanedOptions()
  src/Search.php:2558                                Search::displayCriteria()
  src/Search.php:170                                 Search::showGenericSearch()
  marketplace/archisw/front/swcomponent.php:34       Search::show()
  {"user":"9@glpi"} 
[2022-11-15 12:51:40] glpisqllog.ERROR: DBmysql::query() in /usr/share/glpi/src/DBmysql.php line 370
  *** MySQL query error:
  SQL: SHOW COLUMNS FROM `glpi_plugin_archisw_swcomponents`
  Error: Table 'glpi.glpi_plugin_archisw_swcomponents' doesn't exist
  Backtrace :
  src/DBmysql.php:889                                
  src/CommonDBTM.php:611                             DBmysql->listFields()
  src/CommonDBTM.php:3163                            CommonDBTM->getEmpty()
  src/Search.php:2805                                CommonDBTM->maybeDeleted()
  src/Search.php:2558                                Search::displayCriteria()
  src/Search.php:170                                 Search::showGenericSearch()
  marketplace/archisw/front/swcomponent.php:34       Search::show()
  {"user":"9@glpi","mem_usage":"0.001\", 4.98Mio)"} 
[2022-11-15 12:51:40] glpisqllog.ERROR: DBmysql::query() in /usr/share/glpi/src/DBmysql.php line 370
  *** MySQL query error:
  SQL: SHOW COLUMNS FROM `glpi_plugin_archisw_swcomponents`
  Error: Table 'glpi.glpi_plugin_archisw_swcomponents' doesn't exist
  Backtrace :
`

**Comment by ericferon** [comment]
Hi,
I mean an error message when you activated the plugin.
Can you remove the plugin and reinstall it ?
Then, can you send me the error message(s) related to the installation ?
Thanks,

**Comment by we-sell-bags** [comment]
Ok.
remove it ... no error

reinstalled it but DID NOT activate it.....

`[2022-11-16 17:44:52] glpisqllog.ERROR: DBmysql::query() in /usr/share/glpi/src/DBmysql.php line 370
  *** MySQL query error:
  SQL: SELECT * from glpi_plugin_archisw_swcomponents_itemroles where itemtype = 'PluginArchiswSwcomponent'
  Error: Table 'glpi.glpi_plugin_archisw_swcomponents_itemroles' doesn't exist
  Backtrace :
  marketplace/archisw/hook.php:41                    
  src/Plugin.php:787                                 plugin_archisw_install()
  :                                                  Plugin->install()
  src/Marketplace/Controller.php:545                 call_user_func()
  src/Marketplace/Controller.php:435                 Glpi\Marketplace\Controller->setPluginState()
  ajax/marketplace.php:82                            Glpi\Marketplace\Controller->installPlugin()
  {"user":"9@glpi"} 
[2022-11-16 17:44:52] glpisqllog.ERROR: DBmysql::query() in /usr/share/glpi/src/DBmysql.php line 370
  *** MySQL query error:
  SQL: INSERT INTO glpi_plugin_archisw_swcomponents_itemroles (itemtype,name,comment) VALUES ('PluginArchiswSwcomponent','(To be/Being) Replaced by','Which application will replace this one ?')
  Error: Table 'glpi.glpi_plugin_archisw_swcomponents_itemroles' doesn't exist
  Backtrace :
  src/DBmysql.php:1010                               
  marketplace/archisw/hook.php:42                    DBmysql->runFile()
  src/Plugin.php:787                                 plugin_archisw_install()
  :                                                  Plugin->install()
  src/Marketplace/Controller.php:545                 call_user_func()
  src/Marketplace/Controller.php:435                 Glpi\Marketplace\Controller->setPluginState()
  ajax/marketplace.php:82                            Glpi\Marketplace\Controller->installPlugin()
  {"user":"9@glpi","mem_usage":"0.008\", 4.23Mio)"} 
[2022-11-16 17:44:52] glpisqllog.ERROR: DBmysql::query() in /usr/share/glpi/src/DBmysql.php line 370
  *** MySQL query error:
  SQL: ALTER TABLE `glpi_plugin_archisw_swcomponents` 
   ADD COLUMN IF NOT EXISTS `plugin_archisw_standards_id` INT(11) NOT NULL default '0' COMMENT 'Standard status (Standard, Not standard, ...)' AFTER `plugin_archisw_swcomponentlicenses_id`,
   ADD KEY IF NOT EXISTS `plugin_archisw_standards_id` (`plugin_archisw_standards_id`)
  Error: Table 'glpi.glpi_plugin_archisw_swcomponents' doesn't exist
  Backtrace :
  src/DBmysql.php:1010                               
  marketplace/archisw/hook.php:46                    DBmysql->runFile()
  src/Plugin.php:787                                 plugin_archisw_install()
  :                                                  Plugin->install()
  src/Marketplace/Controller.php:545                 call_user_func()
  src/Marketplace/Controller.php:435                 Glpi\Marketplace\Controller->setPluginState()
  ajax/marketplace.php:82                            Glpi\Marketplace\Controller->installPlugin()
  {"user":"9@glpi","mem_usage":"0.013\", 4.24Mio)"} 
[2022-11-16 17:44:52] glpisqllog.ERROR: DBmysql::query() in /usr/share/glpi/src/DBmysql.php line 370
  *** MySQL query error:
  SQL: ALTER TABLE `glpi_plugin_archisw_swcomponents` 
	ADD COLUMN IF NOT EXISTS `address_qa` varchar(255) default null,
	ADD COLUMN IF NOT EXISTS `repo` varchar(255) collate utf8_unicode_ci default NULL,
	ADD COLUMN IF NOT EXISTS `health_check` varchar(255) collate utf8_unicode_ci DEFAULT NULL
  Error: Table 'glpi.glpi_plugin_archisw_swcomponents' doesn't exist
  Backtrace :
  src/DBmysql.php:1010                               
  marketplace/archisw/hook.php:51                    DBmysql->runFile()
  src/Plugin.php:787                                 plugin_archisw_install()
  :                                                  Plugin->install()
  src/Marketplace/Controller.php:545                 call_user_func()
  src/Marketplace/Controller.php:435                 Glpi\Marketplace\Controller->setPluginState()
  ajax/marketplace.php:82                            Glpi\Marketplace\Controller->installPlugin()
  {"user":"9@glpi","mem_usage":"0.018\", 4.23Mio)"} `

**Comment by ericferon** [comment]
Hi,
Can you check whether there are tables in the GLPI database with names starting with glpi_plugin_archisw ?
If yes, which are they ?
Otherwise can you log into mysql with the GLPI user and pwd, use the GLPI database and "source" the archisw/sql/empty-2.2.2.sql file ? Report any SQL error.
If there are no errors, you can activate the plugin and use it.
K.r,

**Comment by we-sell-bags** [comment]
Hi,
nope , no tables with this name..
hmmm no sql script with that name........

is this a plugin ?

version is:
GLPI 10.0.5 

Nov 15 12:26 empty-1.0.0.sql
Nov 15 12:26 empty-1.0.1.sql
Nov 15 12:26 empty-1.0.2.sql
Nov 15 12:26 empty-2.2.0.sql
Nov 15 12:26 empty-2.2.1.sql
Nov 15 12:26 update-1.0.1.sql
Nov 15 12:26 update-1.0.2.sql
Nov 15 12:26 update-1.0.3.sql
Nov 15 12:26 update-2.2.0.sql
Nov 15 12:26 update-2.2.1.sql`

**Comment by ericferon** [comment]
Hi,
Indeed the file empty-2.2.2.sql is missing in the plugin archive.
It has been added in v2.2.15.
K.r,
