### ISSUE TITLE
No ticket association possible with GLPI 9.2.3

### ISSUE THREAD

**Issue by redfish0** [ericferon/glpi-archisw#6]
Hi running GLPI 9.2.3 with archisw 2.0.2, I cannot create tickets. As soon as the plugin is active the drop-down menu for material selections is empty. With debug enabled I get :

PHP Warning: asort() expects parameter 1 to be array, null given in /var/www/glpi/inc/commonitilobject.class.php at line 4445
PHP Warning: Invalid argument supplied for foreach() in /var/www/glpi/inc/commonitilobject.class.php at line 4458
PHP Warning: array_merge(): Argument #2 is not an array in /var/www/glpi/inc/commonitilobject.class.php at line 4464
PHP Warning: array_keys() expects parameter 1 to be array, null given in /var/www/glpi/inc/item_ticket.class.php at line 653

Any idea what could cause that issue ?

Thank you

Patrick

**Comment by ericferon** [comment]
The involved classes are core ones. So, a priori, the plugin does not seem responsible for this behaviour.
Does it change if you inactivate the plugin ? What does the menu contain in that case ?
Best regards,

**Comment by ericferon** [comment]
Indeed.
The problem is solved in v2.0.3, just released.
Best regards,
