### ISSUE TITLE
Evo : Groupe

### ISSUE THREAD

**Issue by EC2311** [ericferon/glpi-archisw#60]
Hello 

very good job !
(archisw 2.2.9)
Just a remark when attaching a group to application as item : 
all groups are listed, because it's the job of the native fonction of glpi (I think Dropdown::showSelectItemFromItemtypes)
but it will be good to list only the groups which have the 'is assign' = 1, like in the computer (for technical group or user group)

I tried to correct that (by copying the function and ajax and so on) : but not good :( I don't success.
I saw that there was the group::dropdown function too, which may be used, and can list only the "assign" group : but I don't know how to mix it with the Dropdown::showSelectItemFromItemtypes

perhaps you will succeed ?

Thanks

**Comment by ericferon** [comment]
Unfortunately, I cannot do better than you : the Dropdown::showSelectItemFromItemtypes function is part of the GLPI core and I cannot change it to include another condition (is_assign == 1) for displaying only the targeted groups.
K.r,
