### ISSUE TITLE
Link Database object

### ISSUE THREAD

**Issue by karokarov** [ericferon/glpi-archisw#61]
Hello!
Thank you for the very good plugin!

This request is similar to the Issue #59.
For our needs we're desperately missing ability to link 'database' objects to Apps structures. 
That feature would greatly increase the power of the plugin - it would be possible account not only DB type, but the specific instance of the database.

Generaly speaking, ability to assosiate Apps structure to any kind of the element (not limited to the specific hardcoded list) would be very beneficial as giving full flexibility to shape your application.

**Comment by ericferon** [comment]
Hi,
The link to databases existed as long as databases were inventoried with a plugin.
I will add it back, as part of the core, in v3.0.5.
To my knowledge, the classes that can be linked must be listed one by one.
K.r,
