### ISSUE TITLE
Unique names

### ISSUE THREAD

**Issue by PopovIntelkomp** [ericferon/glpi-archisw#62]
Hello!
I noticed an interesting feature. It is not possible to create two objects with the same name, even if they belong to different organizations. Is there any way around this limitation? Thanks!

**Comment by ericferon** [comment]
Hi,
There is, in the GLPI database, a unique key index based on the name among the children of a same parent.
This feature prevents the erroneous creation of duplicates.
But you may suppress this index 'unicity', or change its definition in the database.
A priori, I do not touch indexes once created, but I cannot commit to that ; so, document your change, if any.
K.r,
