### ISSUE TITLE
Bug - App Structures

### ISSUE THREAD

**Issue by Marcelovmz** [ericferon/glpi-archisw#65]
After install the plug-in on version 10.0.9 from GLPI, the Menu Setup doesn't show the App Structures configuration, the same to dropdowns that doesn't show the Field groups to configure.

Version App Structures: 3.0.10
Version GLPI: 10.0.9

**Comment by ericferon** [comment]
Hi,
To my knowledge, it works on GLPI 10.0.9.
If you do not see the menu Setup->Apps structure configuration, check your profile : in the tab Apps Structures, the line "Configuration" must be granted for Read, Update, Create, Put in trashbin or Delete permanently.
K.r,
