### ISSUE TITLE
Translate the plugin

### ISSUE THREAD

**Issue by jcervantes-sipecom** [ericferon/glpi-archisw#68]
Is there any group like Transifex where we can join to help to translate the plugin?

**Comment by ericferon** [comment]
Hi,
Thank you for your proposal to translate the plugin.
There is indeed a Transifex project for this plugin. Another way could be a pull request with the .po and .mo files for your locales.
K.r,

**Comment by jcervantes-sipecom** [comment]
What is the URL? I cannot find it. We prefer translate on Transifex or another web translation tool instead uploading the .po .mo files so we can centralize the work. Thank you. Can you add the es_EC (Español Ecuador) to the translation please?

**Comment by ericferon** [comment]
Hi,
es_EC doesn't seem existing in the list of languages in Transifex. So I propose that you use the spanish language (es_ES) instead of another spanish variant
You can subscribe to the plugin's transifex project here : https://explore.transifex.com/--151/glpi-archisw/.
K.r,

**Comment by jcervantes-sipecom** [comment]
Thank you @ericferon I have sent a request to add the language and join to the project.
