### ISSUE TITLE
Add more types of assoiciated items

### ISSUE THREAD

**Issue by karokarov** [ericferon/glpi-archisw#70]
Dear Developers!
More we use the plugin, more we like it. Thanks for all your efforts!

Would it be possible to add Appliance, Connection, Certificate to the list of associated items to be able to show application dependency on telecom lines, server certificates and some special equipment. 
Many thanks in advance.

**Comment by ericferon** [comment]
Hi,
Appliance was already in the list.
I added Certificate, but Connection does not exist.
From v3.0.16 on.
K.r,

**Comment by ericferon** [comment]
Hi,
The plugin allows association with objects from the "Objects management" plugin, but not with other plugins (than mines :-).
K.r,

**Comment by karokarov** [comment]
Hi,
we tried to adopt "Object management" plugin to maintain Connections inventory, but unfortunately it has no Associated items feature. So we cannot build complete hierarchy of the objects top-down from Application to the low-level network device. 
Unfortunately we're desperated to find any other solution.

Maybe you can give a hint how to modify the list of "Assiciated items" in archisw, so we can give a try to do it ourself?

**Comment by ericferon** [comment]
Hi,
In file .../marketplace/archisw/inc/swcomponent.class.php, line 37, the variable $types contains the list of classes that can be associated.
K.r,
