### ISSUE TITLE
Link with "Network device"

### ISSUE THREAD

**Issue by redfish8** [ericferon/glpi-archisw#71]
Hello,
Seems that the "Network device" type of object cannot be linked with Apps Structure, correct ?
If true could it be an improvement ?

Thank you

Patrick

**Comment by ericferon** [comment]
No, you can associate a network device with an application, via the tab "Associated items" in an app structure entry.
K.r,

**Comment by redfish8** [comment]
You're right, I didn't explain correctly my issue. I can link Network Device but I cannot configure the Link Role. Probably because I mistype the "Type" in the Link role dropdown configuration. It would be nice that the field type does a lookup of the valid Types. For Network device I tried "Network Device" and "Network device", the other link role I successfully setup have a single word Type, like "Appliance". Do you have a clue of the type to set for Network Device.
I apologize for the misleading issue.

**Comment by ericferon** [comment]
You should use "NetworkEquipment".
K.r,
