### ISSUE TITLE
Rules approval request

### ISSUE THREAD

**Issue by alisher372** [ericferon/glpi-archisw#74]
Created rules for tickets that must "Send an approval request - Manager of the requester" but it doesnt work!!
glpi version 10.0.14
glpisqllog.ERROR: DBmysql::doQuery() in /var/www/glpi/src/DBmysql.php line 403
  *** MySQL query error:
  SQL: SELECT * FROM `glpi_plugin_archisw_swcomponents` WHERE `users_id_tech` = '20' AND `is_deleted` = '0'
  Error: Unknown column 'users_id_tech' in 'where clause'
  Backtrace :
  src/DBmysqlIterator.php:112                        DBmysql->doQuery()
  src/DBmysql.php:1109                               DBmysqlIterator->execute()
  src/User.php:5042                                  DBmysql->request()
  src/User.php:326                                   User->showItems()
  src/CommonGLPI.php:694                             User::displayTabContentForItem()
  ajax/common.tabs.php:120                           CommonGLPI::displayStandardTab()
  public/index.php:82                                require()

**Comment by ericferon** [comment]
Hi,
I do not understand the link between your issue and this plugin.
Can you give detail about the path to create your rule, and the parameters of your rule ?
Thank you,
