### ISSUE TITLE
config page is empty after installation

### ISSUE THREAD

**Issue by blackbasket** [ericferon/glpi-archisw#75]
Hi @ericferon ,

I have installed the plugin into a fresh GLPI installation. Where I should see the config, there is only a blank page with "27 ghost entries" (white on white). Refreshing the browser or changing to another one will not change anything.

What can I do?

![grafik](https://github.com/ericferon/glpi-archisw/assets/64146687/99433f85-b87f-4f60-84aa-490dbb789ad2)

Regards,
Marcel

**Comment by ericferon** [comment]
Hi,
Have you error messages in the glpi or php logs (GLPIROOT/files/_log/php-errors.log or sql-errors.log) ?
K.r,

**Comment by blackbasket** [comment]
the only thing might be this one from php-errors

```[2024-04-03 11:34:52] glpiphplog.WARNING:   *** PHP User Warning (512): Usage of signed integers in primary or foreign ke>
  Backtrace :
  src/DBmysql.php:2174                               trigger_error()
  src/DBmysql.php:394                                DBmysql->checkForDeprecatedTableOptions()
  src/DBmysql.php:1080                               DBmysql->doQuery()
  marketplace/archisw/hook.php:34                    DBmysql->runFile()
  src/Plugin.php:922                                 plugin_archisw_install()
  :                                                  Plugin->install()
  src/Marketplace/Controller.php:546                 call_user_func()
  src/Marketplace/Controller.php:436                 Glpi\Marketplace\Controller->setPluginState()
  src/Marketplace/Controller.php:179                 Glpi\Marketplace\Controller->installPlugin()
  ajax/marketplace.php:75                            Glpi\Marketplace\Controller->downloadPlugin()
  public/index.php:82                                require()```

**Comment by ericferon** [comment]
Hi,
There must be an error message somewhere ...
Maybe in your Apache or Nginx log.
Maybe, can you also uninstall and install again the plugin.
K.r,

**Comment by blackbasket** [comment]
Reinstalling helped, thanks :)
