### ISSUE TITLE
Icon for impact analysis

### ISSUE THREAD

**Issue by Giudy** [ericferon/glpi-archisw#77]
+1

**Comment by ericferon** [comment]
Hi,
What do you mean ? There is an icon for impact analysis.
K.r,

**Comment by Giudy** [comment]
yes, but it seems that it does not the job
I see this error in the console
![image](https://github.com/ericferon/glpi-archisw/assets/7987648/e2c45df7-fec0-4280-b285-079e95242def)

is it possible that this line then does not include the hostname?
 $CFG_GLPI['impact_asset_types']['PluginArchiswSwcomponent'] = Plugin::getPhpDir("archisw", false)."/swcomponent.png";
?

dm

**Comment by ericferon** [comment]
Hi,
You are probably right.
Version 3.0.20 should fix the issue.
Can you confirm ?
K.r,

**Comment by Giudy** [comment]
Perfect, thank you!!!
Sorry if at the beginning I didn't check better if it was a feature request or an issue!

davide
