### ISSUE TITLE
Evolution ?

### ISSUE THREAD

**Issue by EC2311** [ericferon/glpi-archisw#8]
How could we manage that an application can be shared/used by some customers (to define) : no notion of customer in GLPI...
Could we imagine to put this notion like an 'attached element', like computer, database ?

**Comment by ericferon** [comment]
The easiest is to reuse some existing objects like entities or users, if you can define your "customers" in such a way. Then, these objects could be linked to an application.
Best regards,

**Comment by EC2311** [comment]
I don't find how to link users or entity with application : only associated elemetns are : database, computer, diagram and projects...
Best regards

**Comment by ericferon** [comment]
I added "User" in the dropdown list of "Associated Items", in v2.0.5

**Comment by EC2311** [comment]
Hello
I downloaded the code : Installation is ok.
nevertheless, I wonder about the role (DEV, PROD) if linked to an user ;) : the dropdown is seen, but not mandatory, so it is not blocking. 

Very well !

Just a question : how to migrate data from appliances pluging towards yours ?

**Comment by ericferon** [comment]
There is no migration tool.
Either you must retype, either you work directly in the database with SQL, depending on the volume to migrate
Best regards,
